### ISSUE TITLE
Getting some errors in Void Linux

### ISSUE THREAD

**Issue by austinrojers** [JezerM/web-greeter#25] opened 2021-12-14 06:31 UTC
## Environment
- OS: Void Linux
- web-greeter version: 3.2.1

## Bug description
I have installed web-greeter and nody-greeter in Void Linux, and I am getting some errors:
```

❯ nody-greeter

2021-12-14 11:57:24 [ DEBUG ] browser.js 121: Initializing Browser Window
2021-12-14 11:57:24 [ DEBUG ] browser.js 137: Browser Window created
2021-12-14 11:57:24 [ DEBUG ] browser.js 118: Theme loaded
2021-12-14 11:57:24 [ DEBUG ] globals.js 15: Javascript logger is ready
2021-12-14 11:57:24 [ DEBUG ] globals.js 12: Window is ready
2021-12-14 11:57:24 [ ERROR ] bridge.js 50: Error: Unable to determine socket to daemon
2021-12-14 11:57:24 [ DEBUG ] bridge.js 65: LightDM API connected
2021-12-14 11:57:27 [ DEBUG ] screensaver.js 44: Screensaver set
2021-12-14 11:57:27 [ DEBUG ] browser.js 155: Nody Greeter started
2021-12-14 11:57:28 [ DEBUG ] screensaver.js 51: Screensaver reset 

❯ web-greeter

2021-12-14 11:57:32 [ DEBUG ] screensaver - screensaver.py:30 : set_screensaver | Screensaver timeout set
2021-12-14 11:57:32 [ DEBUG ] browser - browser.py:208 : init | Initializing Browser Window
2021-12-14 11:57:33 [ DEBUG ] browser - browser.py:252 : init | Browser Window created
2021-12-14 11:57:33 [ DEBUG ] browser - browser.py:157 : show | Window is ready
2021-12-14 11:57:33 [ ERROR ] Greeter.py 152 : __init__ | lightdm_greeter_error: Unable to determine socket to daemon (1)

** (python3:7886): CRITICAL **: 11:57:35.064: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
2021-12-14 11:57:35 [ DEBUG ] Greeter.py 162 : __init__ | LightDM API connected
2021-12-14 11:57:35 [ DEBUG ] browser - browser.py:343 : load_theme | Theme loaded
2021-12-14 11:57:35 [ DEBUG ] browser - browser.py:160 : run | Web Greeter started
2021-12-14 11:57:40 [ DEBUG ] screensaver - screensaver.py:40 : reset_screensaver | Screensaver reset

```

Thank You

**Comment by JezerM** [comment] 2021-12-14 13:10
Those errors are expected if you do not have `X-LightDM-Allow-Greeter=true` inside your xsession (`/usr/share/xsessions/`). As the error dialog says, "You can continue without major problems, but you won't be able to log in".

If there is no other error, everything it's working fine~

**Comment by austinrojers** [comment] 2021-12-14 15:48
I am getting an error while using the _litarvan_  theme in Void Linux only in bot web-greeter and nody-greeter.
I don't get this while running the greeter in a terminal in debug mode, but during system login:

![image](https://user-images.githubusercontent.com/87067093/146031657-489b8052-6f87-46a7-ac0e-3d5e117d3f92.png)

**Comment by JezerM** [comment] 2021-12-14 19:15
That error happens on Litarvan 3.2.0 version, in the next line: https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/b9bce2c777cafe1905056f34b6a719b08a003146/src/translations.js#L210

So, it may be that the Litarvan version you installed is the 3.2.0, but not the master branch. How did you install Litarvan?

**Comment by austinrojers** [comment] 2021-12-15 01:52
> That error happens on Litarvan 3.2.0 version, in the next line: https://github.com/Litarvan/lightdm-webkit-theme-litarvan/blob/b9bce2c777cafe1905056f34b6a719b08a003146/src/translations.js#L210
> 
> So, it may be that the Litarvan version you installed is the 3.2.0, but not the master branch. How did you install Litarvan?


I had `git clone https://github.com/JezerM/lightdm-webkit-theme-litarvan.git`

**Comment by JezerM** [comment] 2021-12-15 02:36
Hmm... That's weird. I'll try to run Void and see what's the problem, though it should work equally in every distro.

If you want to provide more info, run `npx vue-cli-service build --mode dev` inside Litarvan git project, and try `web-greeter --debug --theme dist/index.html`. The log could show where the problem may be located.

**Comment by austinrojers** [comment] 2021-12-15 02:48
```
❯ npx vue-cli-service build --mode dev

⠸  Building for dev...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠧  Building for dev...

 DONE  Compiled successfully in 2739ms                                8:14:15 AM

  File                        Size                    Gzipped

  dist/js/chunk-vendors.js    621.29 KiB              134.64 KiB
  dist/js/app.js              451.75 KiB              50.67 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
❯ web-greeter --debug --theme dist/index.html
2021-12-15 08:15:55 [ DEBUG ] screensaver - screensaver.py:30 : set_screensaver | Screensaver timeout set
2021-12-15 08:15:55 [ DEBUG ] browser - browser.py:208 : init | Initializing Browser Window

DevTools listening on ws://127.0.0.1:12345/devtools/browser/1ed6433d-60a3-43ea-a111-4f1a34217194
NotImplementedError: QLayout.itemAt() is abstract and must be overridden
2021-12-15 08:15:55 [ DEBUG ] browser - browser.py:281 : _initialize_devtools | DevTools initialized
2021-12-15 08:15:55 [ DEBUG ] browser - browser.py:252 : init | Browser Window created
2021-12-15 08:15:55 [ DEBUG ] browser - browser.py:157 : show | Window is ready
2021-12-15 08:15:55 [ DEBUG ] Greeter.py 162 : __init__ | LightDM API connected
2021-12-15 08:15:55 [ DEBUG ] browser - browser.py:343 : load_theme | Theme loaded
2021-12-15 08:15:55 [ DEBUG ] browser - browser.py:160 : run | Web Greeter started
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:12345
2021-12-15 08:16:03 [ DEBUG ] screensaver - screensaver.py:40 : reset_screensaver | Screensaver reset

 ~/Source Packages/web-nody greeter themes/litarvan-build  on master    
```
BTW I don't have such an issue with other themes, and this shows _only during login_, not while _terminal debugging_

**Comment by JezerM** [comment] 2021-12-15 03:15
May it be that Litarvan wasn't installed correctly? Idk, you could try to remove the Litarvan theme inside `/usr/share/web-greeter/themes` and reinstall, with no much hope.

If it does not work, then I don't know what could it be.

**Comment by austinrojers** [comment] 2021-12-15 03:50
I tried, but it didn't work.
But it works in Ubuntu, the same theme files

**Comment by austinrojers** [comment] 2021-12-15 07:44
No worries.
I will use _glorious_ in Void and _litarvan_ in Ubuntu.
Thank you for the help

**Comment by JezerM** [comment] 2021-12-16 01:40
I managed to run Void Linux inside a VM. The problem is that Void does not have a "default" Language, so Litarvan theme broke at some `undefined` property. It should be fixed now in my Litarvan's fork.

**Closed** 2021-12-20 06:01 UTC
Labels: bug

**Comment by austinrojers** [comment] 2021-12-20 07:19
sorry @JezerM, I couldn't reply to your reply.
Two days I had to reinstall my Void Linux due to some other issues.
But now when I try to install web-greeter with the same instructions I followed earlier I am getting this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/web-greeter/__main__.py", line 99, in <module>
  File "/usr/bin/web-greeter/browser/browser.py", line 33, in <module>
  File "/usr/bin/web-greeter/browser/window.py", line 28, in <module>
  File "/usr/bin/web-greeter/bridge/__init__.py", line 129, in <module>
  File "/usr/bin/web-greeter/bridge/Greeter.py", line 30, in <module>
  File "/usr/bin/web-greeter/browser/error_prompt.py", line 32, in <module>
ImportError: /home/austin/.local/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5

```

Sorry it this a trivial issue

**Comment by JezerM** [comment] 2021-12-20 07:43
No worries~

About the web-greeter installation problems, I'd recommend to reinstall PyQt5 and QtWebEngine; this happened sometimes to me in Arch, see [this related answer](https://stackoverflow.com/a/68811630).

Possible packages to reinstall:

- python-PyQt5
- python-pyqt5-webengine
- qt5-webengine

> Do not install them with PIP, xbps dependencies should be enough.

**Comment by austinrojers** [comment] 2021-12-20 17:02
Thank you so much @JezerM, now everything is working in Void Linux!
