### ISSUE TITLE
safe_load() removed

### ISSUE THREAD

**Issue by linuxnoob757** [JezerM/web-greeter#75] opened 2024-03-22 20:26 UTC
## Environment
- OS: Arch
- web-greeter version: 3.5.2

## Bug description
Using lightdm with web-greeter and the [Shikai theme](https://github.com/TheWisker/Shikai). Lightdm is defaulting to gruvbox theme, and I am unable to change it even to dracula theme. Seeing the following error when using web-greeter --debug and in the log file:
2024-03-22 16:17:23 [ ERROR ] config - config.py:209 : load_config | Config was not loaded:
	
"safe_load()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.load(...)

instead of file "/usr/lib/web-greeter/config.py", line 207

            web_greeter_config["config"] = yaml.safe_load(file)

2024-03-22 16:17:23 [ ERROR ] acpi - acpi.py:20 : __init__ | ACPI: acpi_listen does not exists
2024-03-22 16:17:23 [ ERROR ] Greeter - Greeter.py:98 : __init__ | lightdm_greeter_error: Unable to determine socket to daemon (1)

** (python3:16689): CRITICAL **: 16:17:43.092: lightdm_greeter_ensure_shared_data_dir_sync: assertion 'priv->connected' failed
2024-03-22 16:17:43 [ DEBUG ] Greeter - Greeter.py:116 : __init__ | LightDM API connected
2024-03-22 16:17:43 [ WARNING ] config - config.py:180 : load_theme_config | Theme config was not loaded:
	
"safe_load()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.load(...)

instead of file "/usr/lib/web-greeter/config.py", line 176

            theme_config = yaml.safe_load(file)

2024-03-22 16:17:43 [ DEBUG ] config - config.py:181 : load_theme_config | Using default theme config
2024-03-22 16:17:43 [ DEBUG ] browser - browser.py:185 : create_windows | Browser Window created
2024-03-22 16:17:43 [ DEBUG ] screensaver - screensaver.py:57 : set_screensaver | Screensaver timeout set
2024-03-22 16:17:43 [ DEBUG ] browser - browser.py:248 : init | Initializing Browser Window
2024-03-22 16:17:43 [ DEBUG ] browser - browser.py:268 : load_theme | Theme loaded
2024-03-22 16:17:43 [ DEBUG ] browser - browser.py:230 : show | Web Greeter started win: 7859
2024-03-22 16:17:43 [ DEBUG ] browser - browser.py:234 : run | Web Greeter started

## Steps to reproduce
Update all packages with sudo pacman -Syyu then restart or log off.

## Expected behavior
Expected to see shikai theme when starting machine

**Comment by JezerM** [comment] 2024-03-22 21:17
Duplicate of #74

**Closed** 2024-03-22 21:17 UTC
Labels: bug
